# Generated by Django 3.2.9 on 2021-12-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirsysapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(blank=True, choices=[('Programs', (('BSN', 'Nursing Program'), ('BSHM', 'Hospitality Management Program'), ('BSTM', 'Tourism Management Program'), ('BSA', 'Accountancy Program'), ('AB', 'Liberal Arts Program'), ('BS CRIM.', 'Criminology Program'), ('BSBA', 'Business Administration Program'), ('BSCE', 'Civil Engineering Program'), ('BEED', 'Elementary Education Program'), ('BSED', 'Secondary Education Program'), ('BSCS', 'Computer Science Program'), ('J.D.', 'Juris Doctor Program')))], max_length=31, null=True),
        ),
    ]
