# Generated by Django 3.2.9 on 2022-01-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirsysapp', '0002_remove_enduser_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='school_year',
        ),
        migrations.AddField(
            model_name='research',
            name='school_year_from',
            field=models.IntegerField(default=2022),
        ),
        migrations.AddField(
            model_name='research',
            name='school_year_to',
            field=models.IntegerField(default='1948'),
        ),
    ]
