# Generated by Django 3.2.9 on 2021-12-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirsysapp', '0002_alter_program_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enduser',
            name='suffix_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
