# Generated by Django 3.2.9 on 2022-01-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirsysapp', '0003_auto_20220120_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFtoImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_images', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='research',
            name='images',
            field=models.ManyToManyField(to='dirsysapp.PDFtoImages'),
        ),
    ]
