# Generated by Django 3.2.9 on 2021-12-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirsysapp', '0003_auto_20211215_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduser',
            name='suffix_name',
            field=models.CharField(blank=True, choices=[('Suffix', (('Sr', 'Sr.'), ('Jr', 'Jr.'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VII', 'VII'), ('VIII', 'VIII'), ('IX', 'IX'), ('X', 'X'), ('XI', 'XI'), ('XII', 'XII')))], max_length=10, null=True),
        ),
    ]
