# Generated by Django 3.2.9 on 2022-01-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirsysapp', '0004_auto_20220121_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='dirsysapp.PDFtoImages'),
        ),
    ]
