# Generated by Django 3.2.9 on 2021-12-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirsysapp', '0005_alter_research_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='email',
            field=models.EmailField(blank=True, default='N/A', max_length=254, null=True),
        ),
    ]
