# Generated by Django 3.2.9 on 2022-01-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirsysapp', '0005_alter_research_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='images',
        ),
        migrations.AddField(
            model_name='research',
            name='from_images',
            field=models.ManyToManyField(to='dirsysapp.PDFtoImages'),
        ),
        migrations.AddField(
            model_name='research',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='research',
            name='is_faculty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='research',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='research',
            name='school_year_from',
            field=models.IntegerField(default='1948'),
        ),
        migrations.AlterField(
            model_name='research',
            name='school_year_to',
            field=models.IntegerField(default=2022),
        ),
    ]
