# Generated by Django 3.2.9 on 2022-01-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirsysapp', '0006_auto_20220121_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='from_images',
            field=models.ManyToManyField(blank=True, to='dirsysapp.PDFtoImages'),
        ),
    ]
