# Generated by Django 3.2.9 on 2021-12-17 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirsysapp', '0006_enduser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='school_year',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
