# Generated by Django 3.2.9 on 2021-12-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirsysapp', '0007_alter_research_school_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='research',
            name='keyword',
            field=models.ManyToManyField(to='dirsysapp.Keyword'),
        ),
    ]
