# Generated by Django 3.2.9 on 2022-01-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirsysapp', '0007_alter_research_from_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
