# Generated by Django 3.2.9 on 2021-12-18 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dirsysapp', '0008_auto_20211218_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enduser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='enduser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='enduser',
            name='id_number',
        ),
    ]
