# Generated by Django 3.2.9 on 2021-12-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dirsysapp', '0011_alter_research_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='profile',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
